// Variables

let producto = 'Audifonos Gamer'; // Iniciar variable y asignar valor

let disponible; // Iniciamos la variable pero sin valor

// producto = true; // Reasignando el valor de la variable

disponible = true;


let producto1 = 'Computadora',
    disponible1 = true,
    categoria = 'Computadoras';

// var 1disponible;
let _disponible;

// Estilos para las variables
let nombre_producto = 'Monitor HD'; // underscore
let nombreProducto = 'Monitor HD'; // Camelcase
let NombreProducto = 'Monitor HD'; // Pascal Case
let nombreproducto = 'MonitorHD';

console.log(producto);